# Generated by Django 3.0.8 on 2021-06-14 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0003_meal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Options",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was modified",
                        verbose_name="updated at",
                    ),
                ),
                ("meals", models.ManyToManyField(to="menus.Meal")),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menus.Menu"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
