# Generated by Django 3.0.8 on 2021-06-14 03:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0004_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meal",
            options={"ordering": ("id",)},
        ),
        migrations.AlterField(
            model_name="menu",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
