# Generated by Django 3.0.8 on 2021-06-14 03:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0005_auto_20210614_0344"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
