# Generated by Django 3.0.8 on 2021-06-14 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0007_auto_20210614_0353"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="options",
            name="meals",
        ),
        migrations.AddField(
            model_name="menu",
            name="meals",
            field=models.ManyToManyField(through="menus.Options", to="menus.Meal"),
        ),
        migrations.AddField(
            model_name="options",
            name="meal",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="menus.Meal"
            ),
        ),
        migrations.AlterField(
            model_name="options",
            name="menu",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="menus.Menu"
            ),
        ),
    ]
