# Generated by Django 3.0.8 on 2021-06-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="customization",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
