# Generated by Django 3.0.8 on 2021-06-13 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20210613_2201"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was modified",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("mx", "Mexico"),
                            ("br", "Brazil"),
                            ("cn", "Canada"),
                            ("ch", "Chile"),
                            ("co", "Colombia"),
                            ("us", "USA"),
                            ("pr", "Peru"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
